spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    profiles:
      active: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  #  spring:
  #    resources:
  #      static-locations: classpath:/static/
  #
  #  logging:
  #    level:
  #      org.springframework.web: DEBUG
  #      org.springframework.web.servlet: DEBUG

  #spring:
  #
  #  web:
  #    resources:
  #      add-mappings: true
  #
  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/postgres
  #    username: postgres
  #    password: root123
  #    driver-class-name: org.postgresql.Driver
  #
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate.format_sql: true
  #
  #  server:
  #    port: 8080
  #    servlet:
  #      context-path: /
  #
  logging:
    level:
      #      root: INFO
      org.springframework.web: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
#  profiles:
#    active: dev
#
#  cache:
#    type: simple
